<option value="201"> B - Sala 201 - Computo</option>
<option value="202"> B - Sala 202 - Audiovisuales</option>
<option value="203"> B - Sala 203 - Computo</option>
<option value="204"> B - Sala 204 - Audiovisuales</option>
<option value="206"> B - Sala 206 - Audiovisuales</option>
<option value="207"> B - Sala 207 - Computo</option>
<option value="208"> B - Sala 208 - Audiovisuales</option>
<option value="209"> B - Sala 209 - Computo</option>
<option value="301"> B - Sala 301 - Audiovisuales</option>
<option value="302"> B - Sala 302 - Audiovisuales</option>
<option value="Auditorio"> B - Auditorio</option>